name: icon-manual
on:
  workflow_dispatch:
    branches:
    - master
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - package.json

jobs:
  icon_automation:
    name: figma icon automation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: figma icon
      if: ${{ github.event.head_commit.message != "push content" }}
      run: npm install
      run: npm run fetch
      env:
        FIGMA_FILE_URL: ${{ secrets.FIGMA_FILE_URL }}
        FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
        ADUI_ID: ${{secrets.ADUI_ID}}
      run: npm run build
      run: ls
      run: echo "${{ github.event.head_commit.message }} ${{ secrets.AUTHOR }} ${{ secrets.REPO }} ${{ secrets.MAIL }}======================================"
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      # run: |
      #       cd adui-icon
      #       npm publish --access public
    - name: git push
      run: git add .
      run: git commit 'push content'
      run: git push
    # - name: Pushes to another repository
    #   uses: cpina/github-action-push-to-another-repository@master
    #   env:
    #     API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
    #   with:
    #     source-directory: './adui-icon'
    #     destination-github-username: ${{ secrets.AUTHOR }}
    #     destination-repository-name: ${{ secrets.REPO }}
    #     user-email: ${{ secrets.MAIL }}
    #     target-branch: 'main'
#     - run: ls
#     - run: npm publish --access public
#       env:
#         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#     - run: yarn build
#     - name: GitHub Pages
#       uses: crazy-max/ghaction-github-pages@v1.2.5
#       with:
#         build_dir: docs
#       env:
#         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
